version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=achatdb
     - MYSQL_USER=root
     - MYSQL_PASSWORD=root
    volumes:
     - achatdb:/var/lib/mysql

  spring_app:
    image: fehdkh/achat:latest
    container_name: achatspring
    restart: on-failure
    environment:
     - spring.datasource.url=jdbc:mysql://mysqldb:3
